name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  owasp-dependency-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Baixar OWASP Dependency-Check
      - name: Baixar OWASP Dependency-Check
        run: |
          curl -sSL https://github.com/jeremylong/DependencyCheck/releases/download/v6.5.0/dependency-check-6.5.0-release.zip -o dependency-check.zip
          unzip dependency-check.zip

          # Verificar conteúdo extraído
          ls -la

          # Não é necessário mover, o diretório extraído já é 'dependency-check'
          chmod +x dependency-check/bin/dependency-check.sh

      # Rodar OWASP Dependency-Check
      - name: Rodar OWASP Dependency-Check
        run: |
          ./dependency-check/bin/dependency-check.sh --project "TADS-Fasul" --scan ./Semestre-1/ --format "HTML" --out ./relatorios

      # Exibir Relatório
      - name: Exibir Relatório
        run: |
          cat ./relatorios/dependency-check-report.html
