name: Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  owasp-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install .NET SDK (if required for your project)
        run: |
          sudo apt-get update
          sudo apt-get install -y dotnet-sdk-6.0  # Instala o .NET SDK 6.0 (ajuste conforme a versão necessária)

      - name: Download OWASP Dependency-Check
        run: |
          curl -sSL https://github.com/jeremylong/DependencyCheck/releases/download/v6.5.0/dependency-check-6.5.0-release.zip -o dependency-check.zip
          unzip dependency-check.zip
          chmod +x dependency-check/bin/dependency-check.sh

      - name: Run OWASP Dependency-Check
        run: |
          ./dependency-check/bin/dependency-check.sh --project "Security Scan" --scan ./ --format "HTML" --out ./owasp-report --disableAssemblyAnalyzer

      - name: Upload OWASP Report
        uses: actions/upload-artifact@v3
        with:
          name: owasp-report
          path: ./owasp-report

  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh

      - name: Add Trivy to PATH
        run: |
          sudo ln -s /usr/local/bin/trivy /usr/bin/trivy

      - name: Run Trivy
        run: trivy fs . --exit-code 1 --severity HIGH,CRITICAL

      - name: Upload Trivy Report
        uses: actions/upload-artifact@v3
        with:
          name: trivy-report
          path: ./trivy-report.json
